test:
  image: php:8.0-cli
  script:
    - apt-get update && apt-get install -qy unzip git
    - curl -sSf "https://getcomposer.org/installer" | php -- --filename=composer --install-dir=/usr/local/bin
    - composer install
    - vendor/bin/phpstan --memory-limit=-1 --no-progress
    # todo: - vendor/bin/phpunit
    - vendor/bin/ecs --no-error-table --no-progress-bar
