stages:
  - release

default:
  tags:
    - docker
  services:
    - name: docker:dind
      command: ["--registry-mirror", "https://hubprox.xbet.lan:5000"]
  image: "$CI_REGISTRY/web/main/ops/images/ci_runner:1.3.2"
  before_script:
    - echo -n $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY

release:
  stage: release
  script:
    - 'curl -k --header "Job-Token: $CI_JOB_TOKEN" --data tag=$CI_COMMIT_TAG "${CI_API_V4_URL}/projects/$CI_PROJECT_ID/packages/composer"'
  only:
    - tags
