services:
    ApiClientBundle\Http\ResponseFactory:
        public: true
        arguments:
            - '@http_client'
            - '@serializer.mapping.class_metadata_factory'
            - '@serializer.name_converter.metadata_aware'
            - '@property_info'
            - '@property_accessor'

    ApiClientBundle\Http\Client:
        arguments:
            - '@ApiClientBundle\Http\ResponseFactory'

    ApiClientBundle\Service\ApiClientFactory:
        arguments:
            - !tagged_iterator 'api.client'
            - '@ApiClientBundle\Http\Client'

    ApiClientBundle\Maker\QueryMaker:
        arguments:
            - !tagged_iterator 'api.client'
        tags: ['maker.command']
