services:
    ApiClientBundle\Http\ResponseFactory:
        arguments:
            - '@http_client'
            - '@service_container'

    ApiClientBundle\Http\Client:
        arguments:
            - '@ApiClientBundle\Http\ResponseFactory'

    ApiClientBundle\Service\Manager:
        arguments:
            - !tagged_iterator 'api.client'
            - '@ApiClientBundle\Http\Client'
