services:
    ApiClientBundle\Http\ResponseFactory:
        public: true
        arguments:
            - '@http_client'
            - '@serializer'

    ApiClientBundle\Http\Client:
        arguments:
            - '@ApiClientBundle\Http\ResponseFactory'

    ApiClientBundle\Service\ApiClientFactory:
        arguments:
            - !tagged_iterator 'api.client'
            - '@ApiClientBundle\Http\Client'

    ApiClientBundle\Maker\QueryMaker:
        arguments:
            - !tagged_iterator 'api.client'
        tags: ['maker.command']
